### ISSUE TITLE
Color picker box is always white

### ISSUE THREAD

**Issue by wildernessfamily** [cutehaddy/material-kv#1]
First, thank you for creating such an awesome extension. I've been using it for about a month now and it makes working on .kv files so much easier!

When I add a color the VSCode box always shows white. I made sure I had no other color pick extensions installed. Just in case they were interacting with each other.

Ex.
 #:set title_text get_color_from_hex('#f10000')
The little VSCode color picker box is white. It should be red. It's the same for all the lines and no matter what color I choose. Including if I use HEX or RGBA.
![Screenshot1](https://github.com/wildernessfamily/misc/blob/main/Screen%20Shot%202022-02-21%20at%203.41.48%20PM.png?raw=true)
![Screenshot 2](https://github.com/wildernessfamily/misc/blob/main/Screen%20Shot%202022-02-21%20at%203.42.03%20PM.png?raw=true)

Thanks again for all the time you put into this extension.

**Comment by haddiebakrie** [comment]
Hello,
Thanks for reaching out, I would fix that but for now remove the '#' in the
RGB value, it should work for both kivy and the preview. Let me know if
that works.
Thank you

**Comment by wildernessfamily** [comment]
Thanks for the fast response. Removing the # does work. Thank you!!!
Again, thanks for all the time you put into making this awesome extension!

**Comment by haddiebakrie** [comment]
You're welcome!
